remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dr. José Morán
description: The purpose of this website is to share tools, tutorials, and data from my research in the domain of Aerosol Particle Technology.


## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true
